[package]
name = "cuda-builder"
version = "0.1.0"
authors = ["Julia Tatz <tatz.j@husky.neu.edu>"]
description = "Helper lib to build mixed-code cuda crates"
edition = '2018'

[dependencies]
serde_json = "1.0"
regex = "1.1"
ptx-linker = "0.8"
cargo-xbuild = "0.5"

