[package]
name = "cuda-driver"
version = "0.1.0"
authors = ["Julia Tatz <tatz.j@husky.neu.edu>"]
description = "Dynamic bindings for cuda driver"
edition = '2018'

[features]
default = []
nvrtc = []

[dependencies]
derive_more = "0.13"
failure_derive = "0.1"
failure = "0.1"
lazy_static = "1.2"
dlopen_derive = "0.1"
dlopen = "0.1"

[build-dependencies]
bindgen = "0.47"
