[package]
name = "cuda-driver"
version = "0.1.0"
authors = ["Julia Tatz <tatz.j@husky.neu.edu>"]
description = "Dynamic bindings for cuda driver"
edition = '2018'

[features]
default = []
nvrtc = []
dynamic = ["lazy_static", "dlopen", "dlopen_derive"]

[dependencies]
derive_more = "0.14"
failure = "0.1"
failure_derive = "0.1"
lazy_static = { version = "1.2", optional = true }
dlopen = { version = "0.1", optional = true }
dlopen_derive = { version = "0.1", optional = true }
